set (CPACK_GENERATOR STGZ)

return()

# The following does not work on the FreeBSD 11.2 and default CMake.
# For some reason, CPack does not recognize FreeBSD as a valid generator
# TODO: fix

set (CPACK_GENERATOR FreeBSD)

set (CPACK_FREEBSD_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set (CPACK_FREEBSD_PACKAGE_COMMENT ${CPACK_PACKAGE_DESCRIPTION})
set (CPACK_FREEBSD_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION})
set (CPACK_FREEBSD_PACKAGE_WWW ${PROJECT_HOMEPAGE_URL})
set (CPACK_FREEBSD_PACKAGE_LICENSE "Apache-2.0")
set (CPACK_FREEBSD_PACKAGE_MAINTAINER ${CPACK_PACKAGE_CONTACT})
set (CPACK_FREEBSD_PACKAGE_ORIGIN "misc/mull")

