set (CPACK_GENERATOR DEB)

set (CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_CONTACT})
set (CPACK_DEBIAN_PACKAGE_DESCRIPTION ${PROJECT_DESCRIPTION})

set (CPACK_DEBIAN_PACKAGE_DEPENDS "libllvm${LLVM_VERSION_MAJOR}, libxml2, libsqlite3-0")
