name: Mull metadata
description: Mull metadata
runs:
  using: "composite"
  steps:
    - id: metadata
      name: Detect version and release channel
      shell: bash
      run: |
        case $GITHUB_EVENT_NAME in
          "pull_request")
            echo -pr$(grep -Eo "\"number\": [0-9]+" $GITHUB_EVENT_PATH | awk ' { print $2; exit } ') > .mull-ci-version-suffix
            echo testing > .mull-ci-cs-repo
          ;;
          "push")
            case $GITHUB_REF in
              "refs/heads/"*)
                echo -trunk$GITHUB_RUN_NUMBER > .mull-ci-version-suffix
                echo nightly > .mull-ci-cs-repo
              ;;
              "refs/tags/"*)
                echo stable > .mull-ci-cs-repo
                if [ `echo $GITHUB_REF | awk -F/ ' { print $3 } '` != `grep -Eo "MULL_VERSION [0-9.]+" CMakeLists.txt | awk ' { print $2 } '` ];
                then
                  false
                fi
              ;;
              *)
                false
              ;;
            esac
          ;;
          *)
            false
          ;;
        esac
