name: Setup Bazel cache config
description: Generates files with bazel's remote cache configuration
inputs:
  BUILDBUDDY_API_KEY:
    description: 'API key for buildbuddy.io'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Bazel cache
      if: inputs.BUILDBUDDY_API_KEY != null
      shell: bash
      run: |
        echo "" > .bazel.buildbuddy.rc
        echo "common --bes_results_url=https://app.buildbuddy.io/invocation/" >> .bazel.buildbuddy.rc
        echo "common --bes_backend=grpcs://remote.buildbuddy.io" >> .bazel.buildbuddy.rc
        echo "common --remote_cache=grpcs://remote.buildbuddy.io" >> .bazel.buildbuddy.rc
        echo "common --remote_timeout=10m" >> .bazel.buildbuddy.rc
        echo "common --remote_header=x-buildbuddy-api-key=${{inputs.BUILDBUDDY_API_KEY}}" >> .bazel.buildbuddy.rc
    - name: Enable optimized builds
      shell: bash
      run: |
        echo "common --compilation_mode opt" > .bazel.compilation_mode.bazelrc
    # https://arrdem.com/2024/01/11/bazel-glibc/
    - name: Setup Bazel salt
      if: runner.os == 'Linux'
      shell: bash
      run: |
        build_salt=`ldd --version | sha256sum | awk ' {print $1} '`
        echo "" > .bazel.glibc-salt.rc
        echo "common --copt=-DPLATFORM_FINGERPRINT=$build_salt" >> .bazel.glibc-salt.rc
        echo "common --action_env=PLATFORM_FINGERPRINT=$build_salt" >> .bazel.glibc-salt.rc
