name: Setup Bazel cache config
description: Generates a file with bazel's remote cache configuration
inputs:
  BUILDBUDDY_API_KEY:
    description: 'API key for buildbuddy.io'
    required: true
  PLATFORM:
    description: 'Platform identifier for cache segregation (e.g., ubuntu-22.04-x86_64). If not provided, auto-detected from current OS.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Bazel cache
      if: inputs.BUILDBUDDY_API_KEY != null
      shell: bash
      run: |
        echo "" > .bazel.buildbuddy.rc
    - name: Enable optimized builds
      shell: bash
      run: |
        echo "common --compilation_mode opt" > .bazel.compilation_mode.bazelrc
    - name: Add build salt
      shell: bash
      run: |
        if [ -n "${{ inputs.PLATFORM }}" ]; then
          SALT="${{ inputs.PLATFORM }}"
        else
          SALT=$(./infrastructure/build_salt.sh)
        fi
        echo "common --remote_instance_name=$SALT" > .bazel.build_salt.bazelrc
        cat .bazel.build_salt.bazelrc
