FROM {{OS_NAME}}:{{OS_VERSION}}

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim wget ninja-build \
  libz-dev sqlite3 libsqlite3-dev \
  ncurses-dev libstdc++6 \
  binutils liblzma-dev \
  openssh-client
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
  llvm-{{LLVM_VERSION}}-dev \
  libclang-{{LLVM_VERSION}}-dev \
  libc++-{{LLVM_VERSION}}-dev \
  libc++abi-{{LLVM_VERSION}}-dev \
  clang-{{LLVM_VERSION}}
