synchronize_fixtures:
	cd ./custom_test/ && make synchronize_fixtures
	cd ./google_test/google_test/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/and_or_replacement && make synchronize_fixtures
	cd ./simple_test/mutation_operators/and_or_replacement_cpp/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/math_div/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/math_mul/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/math_sub/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/negate_condition/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/remove_void_function/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/replace_assignment/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/replace_call/ && make synchronize_fixtures
	cd ./simple_test/mutation_operators/scalar_value/ && make synchronize_fixtures
	cd ./simple_test/count_letters && make synchronize_fixtures
	cd ./dylibs_and_objects && make synchronize_fixtures

clean:
	cd ./custom_test/ && make clean
	cd ./google_test/google_test/ && make clean
	cd ./simple_test/mutation_operators/and_or_replacement/ && make clean
	cd ./simple_test/mutation_operators/and_or_replacement_cpp/ && make clean
	cd ./simple_test/mutation_operators/math_div/ && make clean
	cd ./simple_test/mutation_operators/math_mul/ && make clean
	cd ./simple_test/mutation_operators/math_sub/ && make clean
	cd ./simple_test/mutation_operators/negate_condition/ && make clean
	cd ./simple_test/mutation_operators/remove_void_function/ && make clean
	cd ./simple_test/mutation_operators/replace_call/ && make clean
	cd ./simple_test/mutation_operators/scalar_value/ && make clean
	cd ./simple_test/count_letters && make clean
	cd ./dylibs_and_objects && make clean

