- name: Setup Ubuntu Machine
  hosts: "{{ host | default('all') }}"

  vars:
    llvm_version: 6.0.0
    platform: ubuntu

    package_extensions:
      - deb

    mull_cxx_flags: -D_GLIBCXX_USE_CXX11_ABI=1

    packages:
      - vim
      - wget
      - git
      - ninja-build
      - libz-dev
      - sqlite3
      - libsqlite3-dev
      - ncurses-dev
      - libstdc++6
      - binutils
      - liblzma-dev
      - python3-pip
      - cmake

  vars_files:
    - helpers/variables.yaml

  tasks:
    - name: Prepare Working Directory
      include_tasks: helpers/working-directory.yaml

    - name: Install Required Packages
      apt:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Install LLVM Packages
      apt:
        name: "{{ llvm_packages }}"
        state: present
      become: true

    - name: Build Mull
      include_tasks: helpers/build-mull.yaml

    - name: LIT Tests
      include_tasks: helpers/lit-tests.yaml

    - name: Integration Tests
      include_tasks: helpers/integration-tests.yaml
