- name: Setup Ubuntu Machine
  hosts: "{{ host | default('all') }}"

  vars:
    llvm_version: 6.0.0
    platform: ubuntu

    package_extensions:
      - deb

    mull_cxx_flags: -D_GLIBCXX_USE_CXX11_ABI=1

    packages:
      - vim
      - wget
      - git
      - ninja-build
      - libz-dev
      - sqlite3
      - libsqlite3-dev
      - ncurses-dev
      - libstdc++6
      - binutils
      - liblzma-dev
      - python3-pip

  vars_files:
    - helpers/variables.yaml

  tasks:
    - name: Prepare Working Directory
      include: helpers/working-directory.yaml

    - name: Install Required Packages
      apt:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Install LLVM Packages
      apt:
        name: "{{ llvm_packages }}"
        state: present
      become: true

    - name: Install Python dependencies
      pip:
        name:
          - lit==0.9.0
          - filecheck==0.0.18
          - cloudsmith-cli==0.26.0
        executable: pip3

    - name: Download CMake
      get_url:
        url: https://github.com/Kitware/CMake/releases/download/v3.16.9/cmake-3.16.9-Linux-x86_64.sh
        dest: "{{ working_dir }}/cmake.sh"
      register: download_cmake

    - name: Install CMake
      shell: sh {{ working_dir }}/cmake.sh --prefix=/usr/local --skip-license
      args:
        creates: /usr/local/bin/cmake
      when: download_cmake.changed
      become: true

    - name: Build Mull
      include: helpers/build-mull.yaml

    - name: LIT Tests
      include: helpers/lit-tests.yaml

    - name: Integration Tests
      include: helpers/integration-tests.yaml
