# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.define "debian" do |cfg|
    cfg.vm.box = "debian/stretch64"
    cfg.ssh.insert_key = false

    cfg.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "debian-playbook.yaml"
      ansible.extra_vars = {
        llvm_version: ENV['LLVM_VERSION'] || '6.0.0'
      }
    end
  end

  config.vm.define "ubuntu" do |cfg|
    cfg.vm.box = "ubuntu/xenial64"
    cfg.ssh.insert_key = false

    cfg.vm.provision "shell", inline: "apt-get install -y python"

    cfg.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ubuntu-playbook.yaml"
      ansible.extra_vars = {
        llvm_version: ENV['LLVM_VERSION'] || '6.0.0'
      }
    end
  end

end

