---
- name: "Install Python dependencies for LIT: lit and filecheck"
  pip:
    name:
      - lit==0.9.0
      - filecheck==0.0.7
    executable: pip3

- name: Run LIT tests
  make:
    chdir: "{{ source_dir }}/tests-lit"
    target: test
    params:
      PWD: "{{ source_dir }}/tests-lit"
      CLANG_EXEC: "{{ llvm_dir }}/bin/clang++"
