---
- name: Run LIT tests (Debug)
  command: ninja tests-lit
  args:
    chdir: "{{ debug_build_dir }}"

- name: Run LIT tests (Release)
  command: ninja tests-lit
  args:
    chdir: "{{ release_build_dir }}"
