---
gitref: main
repo_url: https://github.com/mull-project/mull.git
working_dir: /opt
SDKROOT: /

llvm_mapping:
  macos:
    13.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-13.0.0-x86_64-apple-darwin
    12.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-12.0.0-x86_64-apple-darwin
    11.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-11.0.0-x86_64-apple-darwin
    10.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-10.0.0-x86_64-apple-darwin
    9.0.0:
      url: http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-darwin-apple.tar.xz
      path: clang+llvm-9.0.0-x86_64-darwin-apple
    8.0.0:
      url: https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-8.0.0-x86_64-apple-darwin
    7.0.0:
      url: https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-7.0.0-x86_64-apple-darwin
    6.0.0:
      url: https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-6.0.0-x86_64-apple-darwin

  debian:
    6.0.0:
      url: https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-debian8.tar.xz
      path: clang+llvm-6.0.0-x86_64-linux-gnu-debian8

  ubuntu:
    13.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
      path: clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04
    12.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
      path: clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04
    11.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
      path: clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04
    10.0.0:
      url: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
      path: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04
    9.0.0:
      url: http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
      path: clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04
    8.0.0:
      url: https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04
    7.0.0:
      url: https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04
    6.0.0:
      url: https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04

  fedora:
    6.0.0:
      url: http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-Fedora27.tar.xz
      path: clang+llvm-6.0.0-x86_64-linux-gnu-Fedora27

  freebsd:
    8.0.0:
      url: http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-amd64-unknown-freebsd11.tar.xz
      path: clang+llvm-8.0.0-amd64-unknown-freebsd11


llvm_url: "{{ llvm_mapping[platform][llvm_version].url }}"
llvm_path: "{{ llvm_mapping[platform][llvm_version].path }}"
llvm_dir: "{{ working_dir }}/llvm-{{ llvm_version }}"
llvm_major: "{{ llvm_version.split('.')[0] }}"

source_dir: "{{ working_dir }}/mull"
debug_build_dir: "{{ working_dir }}/build.mull.debug.dir"
release_build_dir: "{{ working_dir }}/build.mull.release.dir"

checkout: false

# Overriden by FreeBSD playbook
make_program: make
