---
gitref: main
repo_url: https://github.com/mull-project/mull.git
working_dir: /opt
SDKROOT: /

llvm_mapping:
  macos:
    "16":
      cmake_search_paths: "/opt/homebrew/opt/llvm@16/lib/cmake/llvm/;/opt/homebrew/opt/llvm@16/lib/cmake/clang/"
      packages:
        - llvm@16
      cmake_cc: /opt/homebrew/opt/llvm@16/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@16/bin/clang++
    "15":
      cmake_search_paths: "/opt/homebrew/opt/llvm@15/lib/cmake/llvm/;/opt/homebrew/opt/llvm@15/lib/cmake/clang/"
      packages:
        - llvm@15
      cmake_cc: /opt/homebrew/opt/llvm@15/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@15/bin/clang++
    "14":
      cmake_search_paths: "/opt/homebrew/opt/llvm@14/lib/cmake/llvm/;/opt/homebrew/opt/llvm@14/lib/cmake/clang/"
      packages:
        - llvm@14
      cmake_cc: /opt/homebrew/opt/llvm@14/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@14/bin/clang++
    "13":
      cmake_search_paths: "/opt/homebrew/opt/llvm@13/lib/cmake/llvm/;/opt/homebrew/opt/llvm@13/lib/cmake/clang/"
      packages:
        - llvm@13
      cmake_cc: /opt/homebrew/opt/llvm@13/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@13/bin/clang++
    "12":
      cmake_search_paths: "/opt/homebrew/opt/llvm@12/lib/cmake/llvm/;/opt/homebrew/opt/llvm@12/lib/cmake/clang/"
      packages:
        - llvm@12
      cmake_cc: /opt/homebrew/opt/llvm@12/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@12/bin/clang++

  ubuntu:
    "15":
      cmake_search_paths: "/usr/lib/llvm-15/cmake/;/usr/lib/cmake/clang-15/"
      packages:
        - llvm-15-dev
        - libclang-15-dev
        - libc++-15-dev
        - libc++abi-15-dev
        - clang-15
      cmake_cc: clang-15
      cmake_cxx: clang++-15
    "14":
      cmake_search_paths: "/usr/lib/llvm-14/cmake/;/usr/lib/cmake/clang-14/"
      packages:
        - llvm-14-dev
        - libclang-14-dev
        - libc++-14-dev
        - libc++abi-14-dev
        - clang-14
      cmake_cc: clang-14
      cmake_cxx: clang++-14
    "13":
      cmake_search_paths: "/usr/lib/llvm-13/cmake/;/usr/lib/cmake/clang-13/"
      packages:
        - llvm-13-dev
        - libclang-13-dev
        - libc++-13-dev
        - libc++abi-13-dev
        - clang-13
      cmake_cc: clang-13
      cmake_cxx: clang++-13
    "12":
      cmake_search_paths: "/usr/lib/llvm-12/cmake/;/usr/lib/cmake/clang-12/"
      packages:
        - llvm-12-dev
        - libclang-12-dev
        - libc++-12-dev
        - libc++abi-12-dev
        - clang-12
      cmake_cc: clang-12
      cmake_cxx: clang++-12

source_dir: "{{ working_dir }}/mull"
debug_build_dir: "{{ working_dir }}/build.mull.debug.dir"
release_build_dir: "{{ working_dir }}/build.mull.release.dir"

checkout: false

# Overriden by FreeBSD playbook
make_program: make

cmake_search_paths: "{{ llvm_mapping[platform][llvm_version].cmake_search_paths }}"
llvm_packages: "{{ llvm_mapping[platform][llvm_version].packages }}"
cmake_c_compiler: "{{ llvm_mapping[platform][llvm_version].cmake_cc }}"
cmake_cxx_compiler: "{{ llvm_mapping[platform][llvm_version].cmake_cxx }}"
pass_manager_flag: "{{ '' if llvm_version | int > 15 else '-fexperimental-new-pass-manager' }}"
test_mull_config: "{{ source_dir }}/infrastructure/helpers/mull.yml"
