---
gitref: master
repo_url: https://github.com/mull-project/mull.git
working_dir: /opt

llvm_mapping:
  macos:
    8.0.0:
      url: https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-8.0.0-x86_64-apple-darwin
    7.0.0:
      url: https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-7.0.0-x86_64-apple-darwin
    6.0.0:
      url: https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-6.0.0-x86_64-apple-darwin
    5.0.0:
      url: https://releases.llvm.org/5.0.0/clang+llvm-5.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-5.0.0-x86_64-apple-darwin
    4.0.0:
      url: https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-4.0.0-x86_64-apple-darwin
    3.9.0:
      url: https://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
      path: clang+llvm-3.9.0-x86_64-apple-darwin

  debian:
    6.0.0:
      url: https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-debian8.tar.xz
      path: clang+llvm-6.0.0-x86_64-linux-gnu-debian8
    5.0.0:
      url: https://releases.llvm.org/5.0.0/clang+llvm-5.0.0-x86_64-linux-gnu-debian8.tar.xz
      path: clang+llvm-5.0.0-x86_64-linux-gnu-debian8
    4.0.0:
      url: https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-debian8.tar.xz
      path: clang+llvm-4.0.0-x86_64-linux-gnu-debian8
    3.9.0:
      url: https://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-debian8.tar.xz
      path: clang+llvm-3.9.0-x86_64-linux-gnu-debian8

  ubuntu:
    8.0.0:
      url: https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04
    7.0.0:
      url: https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04
    6.0.0:
      url: https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04
    5.0.0:
      url: https://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04.tar.xz
      path: clang+llvm-5.0.0-linux-x86_64-ubuntu16.04
    4.0.0:
      url: https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04
    3.9.0:
      url: https://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      path: clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.04

  fedora:
    6.0.0:
      url: http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-Fedora27.tar.xz
      path: clang+llvm-6.0.0-x86_64-linux-gnu-Fedora27


llvm_url: "{{ llvm_mapping[platform][llvm_version].url }}"
llvm_path: "{{ llvm_mapping[platform][llvm_version].path }}"
llvm_dir: "{{ working_dir }}/llvm-{{ llvm_version }}"

source_dir: "{{ working_dir }}/mull"
build_dir: "{{ working_dir }}/build.mull.dir"

