---
gitref: main
repo_url: https://github.com/mull-project/mull.git
working_dir: /opt
SDKROOT: /

llvm_mapping:
  macos:
    "18":
      cmake_search_paths: "/opt/homebrew/opt/llvm@18/lib/cmake/llvm/;/opt/homebrew/opt/llvm@18/lib/cmake/clang/"
      packages:
        - llvm@18
      cmake_cc: /opt/homebrew/opt/llvm@18/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@18/bin/clang++
    "17":
      cmake_search_paths: "/opt/homebrew/opt/llvm@17/lib/cmake/llvm/;/opt/homebrew/opt/llvm@17/lib/cmake/clang/"
      packages:
        - llvm@17
      cmake_cc: /opt/homebrew/opt/llvm@17/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@17/bin/clang++
    "16":
      cmake_search_paths: "/opt/homebrew/opt/llvm@16/lib/cmake/llvm/;/opt/homebrew/opt/llvm@16/lib/cmake/clang/"
      packages:
        - llvm@16
      cmake_cc: /opt/homebrew/opt/llvm@16/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@16/bin/clang++
    "15":
      cmake_search_paths: "/opt/homebrew/opt/llvm@15/lib/cmake/llvm/;/opt/homebrew/opt/llvm@15/lib/cmake/clang/"
      packages:
        - llvm@15
      cmake_cc: /opt/homebrew/opt/llvm@15/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@15/bin/clang++
    "14":
      cmake_search_paths: "/opt/homebrew/opt/llvm@14/lib/cmake/llvm/;/opt/homebrew/opt/llvm@14/lib/cmake/clang/"
      packages:
        - llvm@14
      cmake_cc: /opt/homebrew/opt/llvm@14/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@14/bin/clang++
    "13":
      cmake_search_paths: "/opt/homebrew/opt/llvm@13/lib/cmake/llvm/;/opt/homebrew/opt/llvm@13/lib/cmake/clang/"
      packages:
        - llvm@13
      cmake_cc: /opt/homebrew/opt/llvm@13/bin/clang
      cmake_cxx: /opt/homebrew/opt/llvm@13/bin/clang++

source_dir: "{{ working_dir }}/mull"
debug_build_dir: "{{ working_dir }}/build.mull.debug.dir"
release_build_dir: "{{ working_dir }}/build.mull.release.dir"

checkout: false

cmake_search_paths: "{{ llvm_mapping[platform][llvm_version].cmake_search_paths }}"
llvm_packages: "{{ llvm_mapping[platform][llvm_version].packages }}"
cmake_c_compiler: "{{ llvm_mapping[platform][llvm_version].cmake_cc }}"
cmake_cxx_compiler: "{{ llvm_mapping[platform][llvm_version].cmake_cxx }}"
pass_manager_flag: "{{ '' if llvm_version | int > 15 else '-fexperimental-new-pass-manager' }}"
test_mull_config: "{{ source_dir }}/infrastructure/helpers/mull.yml"
