name: Ubuntu CI

env:
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - OS_NAME: "ubuntu"
            OS_VERSION: "20.04"
            LLVM_VERSION: 12
          - OS_NAME: "ubuntu"
            OS_VERSION: "22.04"
            LLVM_VERSION: 13
          - OS_NAME: "ubuntu"
            OS_VERSION: "22.04"
            LLVM_VERSION: 14
          - OS_NAME: "ubuntu"
            OS_VERSION: "22.04"
            LLVM_VERSION: 15
          - OS_NAME: "ubuntu"
            OS_VERSION: "24.04"
            LLVM_VERSION: 14
          - OS_NAME: "ubuntu"
            OS_VERSION: "24.04"
            LLVM_VERSION: 15
          - OS_NAME: "ubuntu"
            OS_VERSION: "24.04"
            LLVM_VERSION: 16
          - OS_NAME: "ubuntu"
            OS_VERSION: "24.04"
            LLVM_VERSION: 17
          - OS_NAME: "ubuntu"
            OS_VERSION: "24.04"
            LLVM_VERSION: 18
    name: Ubuntu ${{ matrix.OS_VERSION }} - LLVM ${{ matrix.LLVM_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-package-metadata
        id: metadata
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, test, package
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mull-project/internal-${{ matrix.OS_NAME }}_${{ matrix.OS_VERSION }}_${{ matrix.LLVM_VERSION }}-ci
          configFile: ./.devcontainer/${{ matrix.OS_NAME }}_${{ matrix.OS_VERSION }}_${{ matrix.LLVM_VERSION }}/devcontainer.json
          runCmd: |
            cmake --preset mull -DMULL_VERSION=${{ steps.metadata.outputs.version }}${{ steps.metadata.outputs.suffix }}
            cmake --workflow --preset build-and-test
            cmake --workflow --preset package
            ./tests/end2end/run_end2end_tests.sh ${{ matrix.OS_NAME }} ${{ matrix.LLVM_VERSION }}
            mull-runner-${{ matrix.LLVM_VERSION }} --version

      - name: Publish package
        uses: devcontainers/ci@v0.3
        if: env.CLOUDSMITH_API_KEY != null
        with:
          imageName: ghcr.io/mull-project/internal-${{ matrix.OS_NAME }}_${{ matrix.OS_VERSION }}_${{ matrix.LLVM_VERSION }}-ci
          configFile: ./.devcontainer/${{ matrix.OS_NAME }}_${{ matrix.OS_VERSION }}_${{ matrix.LLVM_VERSION }}/devcontainer.json
          push: never
          runCmd: |
            UBUNTU_CODENAME=$(. /etc/os-release; echo "${UBUNTU_CODENAME/*, /}")
            env CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} cloudsmith push deb \
              mull-project/mull-${{ steps.metadata.outputs.channel }}/${{ matrix.OS_NAME }}/${UBUNTU_CODENAME} \
              build.${{ matrix.OS_NAME }}.${{ matrix.LLVM_VERSION }}.dir/*.deb

      - name: Move package
        run: |
          mkdir -p /tmp/packages
          sudo mv build.${{ matrix.OS_NAME }}.${{ matrix.LLVM_VERSION }}.dir/*.deb /tmp/packages/

      - uses: ./.github/actions/attach-package
        with:
          GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
